# Generated by Django 5.0.2 on 2024-02-26 16:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='user_avatar', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'png', 'heic'))]),
        ),
    ]
