# Generated by Django 5.0.1 on 2024-03-04 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_about_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='location',
            field=models.CharField(max_length=450),
        ),
    ]
