# Generated by Django 5.0.1 on 2024-03-06 15:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_about_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
